# -*- coding: utf-8 -*-
"""teste_img_process_pcg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f8kI8OU-bied9E_8TKp57W3bVcvjngji
"""

from image_processing.utils import io, plot
from image_processing.processing import combination, transformation

image1 = io.read_image(caminho_da_imagem/nomedaimg.jpg)
image2 = io.read_image(caminho_da_imagem2/nomedaimg2.jpg)

plot.plot_image(image1)
plot.plot_image(image2)

result_image = combination.transfer_histogram(image1, image2)
plot.plot_result(image1, image2, result_image)

